# Generated by Django 4.2 on 2023-04-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("airlines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=8)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircrafts",
                        to="airlines.airline",
                    ),
                ),
            ],
        ),
    ]
