version: "3"

services:
  react:
    image: atmc/frontend:0.1.0-dev
    container_name: atmc-frontend-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app:z
    ports:
      - 3000:3000
    command: /usr/bin/docker-start.sh
