# Generated by Django 4.2 on 2023-05-01 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("airlines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=8)),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[("A", "Airbus"), ("B", "Boeing")], max_length=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircrafts",
                        to="airlines.airline",
                    ),
                ),
            ],
        ),
    ]
