# Generated by Django 4.2 on 2023-04-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aircrafts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=16, unique=True)),
                ("alias", models.CharField(max_length=16, null=True, unique=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="aircrafts.aircraft",
                    ),
                ),
            ],
        ),
    ]
