# Generated by Django 4.2 on 2023-05-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        verbose_name="ICAO Airline Designator",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("call_sign", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
